backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/services/index.md'
        label: 'Services Page'
        name: 'services'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'services-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
      - file: 'src/pages/directions/index.md'
        label: 'Directions Page'
        name: 'directions'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'directions-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
              label: Address,
              name: address,
              widget: object,
              fields:
                [
                  { label: Line1, name: line1, widget: string },
                  { label: Line2, name: line2, widget: string },
                ],
            }
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Number, name: number, widget: string },
                  { label: Email, name: email, widget: string },
                ],
            }
          - {
              label: Hours,
              name: hours,
              widget: object,
              fields:
                [
                  { label: MonthruFri, name: monthrufri, widget: string },
                  { label: SatSun, name: satsun, widget: string },
                ],
            }
          - {
              label: Maps,
              name: maps,
              widget: object,
              fields:
                [
                  {
                    label: Closeup,
                    name: close,
                    widget: object,
                    fields:
                      [
                        { label: Alt, name: alt, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                  {
                    label: Wide View,
                    name: wide,
                    widget: object,
                    fields:
                      [
                        { label: Alt, name: alt, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
      - file: 'src/pages/calendar/index.md'
        label: 'Calendar Page'
        name: 'calendar'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'calendar-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: blurb, name: calendarBlurb, widget: string }
          - { label: Picture, name: calendarPicture, widget: picture }
          - { label: Link, name: calendarLink, widget: string }
      - file: 'src/pages/volunteers/index.md'
        label: 'Volunteers Page'
        name: 'volunteer'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'volunteers-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: picture }
          - { label: List Title, name: lefttitle, widget: string }
          - { label: Link, name: calendarLink, widget: string }
          - {
              label: List Contents,
              name: leftlist,
              widget: list,
              fields: [{ label: Text, name: text, widget: text }],
            }
          - { label: Main Text, name: maintext, widget: string }
          - { label: Volunteer Handbook, name: handbook, widget: file }
          - { label: Volunteer Release, name: release, widget: file }
      # - file: 'src/pages/services/index.md'
      # - file: 'src/pages/services/index.md'
